### ISSUE TITLE
Initial charge must succeed

### ISSUE THREAD

**Issue by EGreg** [Intercoin/SubcriptionContract#6]
When a subscription starts, it must charge the user for the first N = intervalsMin intervals upfront.

If this charge fails, then the subscription should fail, too. Just move call to charge() earlier in the method, and if charge failed, return early:

https://github.com/Intercoin/SubcriptionContract/blob/main/contracts/SubscriptionsManagerUpgradeable.sol

The AuctionForSubscriptions contract should have N as a parameter, and the user bids for N intervals at once, then claim() sends this amount back to the user and starts a subscription on their behalf, with that price. But the transfer from user to SubscriptionManager has to succeed or the transaction will be reverted by SubscriptionManager (and thus Auction will catch this and refund the money to the caller).

Remember to send along all the gas (I think is by default) when calling from Auction contract so internal transaction doesn’t fail for out-of-gas reason

**Comment by artman325** [comment]
Done in https://github.com/Intercoin/SubcriptionContract/commit/ed8acb289b71a484790957d7acbc06258994888e
now if pay will not consume. Transaction will revert
